### ISSUE TITLE
fix issueblogger bug

### ISSUE THREAD

**Issue by m-c-frank** [m-c-frank/justthoughts#68]
un docker run --rm -e OPENAI_API_KEY -v /home/runner/work/justthoughts/justthoughts:/data issueblogger python /usr/src/app/scripts/issueblogger.py /data/issue_data.json
  File "/usr/src/app/scripts/issueblogger.py", line 57
    with open(f'blog/{issue_data['number']}-new-post.md', 'w') as file:
                                  ^
SyntaxError: f-string: unmatched '['
Error: Process completed with exit code 1.

**Comment by m-c-frank** [comment]
merged into scripts

**Comment by m-c-frank** [comment]
new bug: Run docker run --rm -e OPENAI_API_KEY -v /home/runner/work/justthoughts/justthoughts:/data issueblogger python /usr/src/app/scripts/issueblogger.py /data/issue_data.json
  
Traceback (most recent call last):
  File "/usr/src/app/scripts/issueblogger.py", line 63, in <module>
    generate_blog_post(issue_file, api_key)
  File "/usr/src/app/scripts/issueblogger.py", line 43, in generate_blog_post
    llm = OpenAI(api_key)
TypeError: __new__() takes 1 positional argument but 2 were given
Error: Process completed with exit code 1.

**Comment by m-c-frank** [comment]
Run docker run --rm -e OPENAI_API_KEY -v /home/runner/work/justthoughts/justthoughts:/data issueblogger python /usr/src/app/scripts/issueblogger.py /data/issue_data.json
  
Traceback (most recent call last):
  File "/usr/local/lib/python3.[9](https://github.com/m-c-frank/justthoughts/actions/runs/6966386645/job/18956459400#step:6:9)/site-packages/langchain/llms/openai.py", line 2[9](https://github.com/m-c-frank/justthoughts/actions/runs/6966386645/job/18956459400#step:6:10)4, in validate_environment
    import openai
ModuleNotFoundError: No module named 'openai'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/scripts/issueblogger.py", line 63, in <module>
    generate_blog_post(issue_file, api_key)
  File "/usr/src/app/scripts/issueblogger.py", line 43, in generate_blog_post
    llm = OpenAI()
  File "/usr/local/lib/python3.9/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/usr/local/lib/python3.9/site-packages/pydantic/v1/main.py", line 1[10](https://github.com/m-c-frank/justthoughts/actions/runs/6966386645/job/18956459400#step:6:11)2, in validate_model
    values = validator(cls_, values)
  File "/usr/local/lib/python3.9/site-packages/langchain/llms/openai.py", line 296, in validate_environment
    raise ImportError(
ImportError: Could not import openai python package. Please install it with `pip install openai`.
Error: Process completed with exit code 1.

**Comment by m-c-frank** [comment]
Run docker run --rm -e OPENAI_API_KEY -v /home/runner/work/justthoughts/justthoughts:/data issueblogger python /usr/src/app/scripts/issueblogger.py /data/issue_data.json
  
Traceback (most recent call last):
  File "/usr/src/app/scripts/issueblogger.py", line 63, in <module>
    generate_blog_post(issue_file, api_key)
  File "/usr/src/app/scripts/issueblogger.py", line 48, in generate_blog_post
    summary = create_and_run_chain(llm, SUMMARY_PROMPT, issue_data['body'])
  File "/usr/src/app/scripts/issueblogger.py", line 40, in create_and_run_chain
    return chain.invoke({'text': input_text}).content
  File "/usr/local/lib/python3.[9](https://github.com/m-c-frank/justthoughts/actions/runs/6966402944/job/18956497955#step:6:9)/site-packages/langchain/chains/base.py", line 87, in invoke
    return self(
  File "/usr/local/lib/python3.[9](https://github.com/m-c-frank/justthoughts/actions/runs/6966402944/job/18956497955#step:6:10)/site-packages/langchain/chains/base.py", line 286, in __call__
    inputs = self.prep_inputs(inputs)
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/base.py", line 443, in prep_inputs
    self._validate_inputs(inputs)
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/base.py", line [19](https://github.com/m-c-frank/justthoughts/actions/runs/6966402944/job/18956497955#step:6:20)5, in _validate_inputs
    raise ValueError(f"Missing some input keys: {missing_keys}")
ValueError: Missing some input keys: {'issue_comments', 'issue_title', 'issue_body'}
Error: Process completed with exit code 1.

**Comment by m-c-frank** [comment]
using new workflow

**Comment by m-c-frank** [comment]
this sucks

**Comment by m-c-frank** [comment]
now logging to pin the issue down

**Comment by m-c-frank** [comment]
closing for test
